title: Shayla Tran

# Setup Lanyon theme
theme: jekyll-theme-lanyon

# Build settings
markdown: kramdown
permalink: pretty

# Plugins (if needed)
plugins:
  - jekyll-feed

# Sidebar links
nav:
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

