title: Portfolio of Shayla Tran
logo: /assets/img/logo.png
description: A collection of previous projects to highlight my work using regression analyses and data visualization.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
