title: Shayla Tran
logo: https://github.com/shaytran/Shayla_Portfolio/blob/main/images/shay.png
description: >
  I am a recent graduate from McGill University in Honours Anatomy and Cell Biology, passionate about healthcare and data analytics. I grew up in Penticton, BC, and am currently furthering my skills in the UBC Master of Data Science program, set to graduate in June. <br><br> 
  My projects center around applying data science to uncover trends, with an emphasis in the healthcare field. With a foundation in R and Python, I aim to simplify complex data into clear insights for practical use. The core of my work lies in predicting future patterns and improving decision-making in diverse fields.
show_downloads: false
google_analytics:
theme: jekyll-theme-minima
